import Social
import UniformTypeIdentifiers
final class ShareViewController:SLComposeServiceViewController{
 override func isContentValid()->Bool{true}
 override func didSelectPost(){let group=DispatchGroup();let lock=NSLock();var rows:[[String:Any]]=[];let now=Int64(Date().timeIntervalSince1970*1000);if !contentText.isEmpty{rows.append(row(kind:1,value:contentText,mime:"text/plain",time:now))};for item in extensionContext?.inputItems as?[NSExtensionItem] ?? []{for provider in item.attachments ?? []{if provider.hasItemConformingToTypeIdentifier(UTType.url.identifier){group.enter();provider.loadItem(forTypeIdentifier:UTType.url.identifier){value,_ in if let url=value as?URL{lock.lock();rows.append(self.row(kind:url.isFileURL ? 3:2,value:url.absoluteString,mime:url.isFileURL ? "application/octet-stream":"text/uri-list",time:now));lock.unlock()};group.leave()}}else if provider.hasItemConformingToTypeIdentifier(UTType.data.identifier){group.enter();provider.loadFileRepresentation(forTypeIdentifier:UTType.data.identifier){url,_ in if let url,let copied=self.copyToGroup(url){lock.lock();rows.append(self.row(kind:3,value:copied,mime:provider.registeredTypeIdentifiers.first ?? "application/octet-stream",time:now));lock.unlock()};group.leave()}}}};group.notify(queue:.main){self.append(rows);self.extensionContext?.completeRequest(returningItems:[])}}
 private func row(kind:Int,value:String,mime:String,time:Int64)->[String:Any]{["id":UUID().uuidString,"kind":kind,"value":String(value.prefix(8192)),"mimeType":String(mime.prefix(255)),"createdAtMillis":time]}
 private var groupName:String?{Bundle.main.object(forInfoDictionaryKey:"PamNativeAppGroup")as?String};private func copyToGroup(_ source:URL)->String?{guard let groupName,let root=FileManager.default.containerURL(forSecurityApplicationGroupIdentifier:groupName)else{return nil};let inbox=root.appendingPathComponent("pam-share-inbox",isDirectory:true);try?FileManager.default.createDirectory(at:inbox,withIntermediateDirectories:true);let name=UUID().uuidString;do{try FileManager.default.copyItem(at:source,to:inbox.appendingPathComponent(name));return name}catch{return nil}}
 private func append(_ rows:[[String:Any]]){guard let groupName,let defaults=UserDefaults(suiteName:groupName)else{return};var existing=defaults.array(forKey:"pam.share.items")as?[[String:Any]] ?? [];existing.append(contentsOf:rows);defaults.set(Array(existing.suffix(256)),forKey:"pam.share.items")}
 override func configurationItems()->[Any]!{[]}
}
